# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursePremium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='user',
            field=models.CharField(help_text='Username', max_length=24),
        ),
    ]
